#!/bin/bash
Task 0 - The command 'su betty' is to switch user to betty
Task 1 - The command 'whoami' print the effective username of the user
Task 2 - The command 'groups' is to print all groups the current user is a part of
Task 3 - the command 'chown betty hello' to change ownership of hello to user betty
Task 4 - The command 'touch hello' is to create an empty file named hello
Task 5 - The command 'chmod u+x hello' is to make the file executable for owner
Task 6 - The command 'chmod ug+x,o+r hello' is add execute permission for owner and group owner, read permission for other users
Task 7 - The command 'chmod ugo+x' to add execute permission for owner, group owner and other users
